language: elixir
dist: bionic
elixir:
  - 1.8.2
otp_release:
  - 22.0

addons:
  postgresql: "9.6"
  apt:
    packages:
      - chromium-chromedriver
services:
  - redis-server

env:
  global:
    - MIX_ENV=test
    - TRAVIS_NODE_VERSION="10.15.2"

cache:
  yarn: true
  directories: — /home/travis/.rvm/
    - node_modules

before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn

before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - nohup chromedriver &
  - echo `chromium-browser --version`
  - echo `chromedriver --version`
  - cd assets && yarn && cd ..

script:
  - mix test --max-cases 1
  - cd assets && yarn run deploy
