language: elixir
dist: bionic
elixir:
  - 1.8.2
otp_release:
  - 22.0

addons:
  postgresql: "9.6"
  apt:
    packages:
      - chromium-chromedriver
services:
  - redis-server

env:
  global:
    - MIX_ENV=test
    - TRAVIS_NODE_VERSION="10.15.2"

cache:
  yarn: true
  directories: — /home/travis/.rvm/
    - node_modules

before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn

before_script:
  - echo `chromium-browser --version`
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - echo `chromedriver --version`
  - cd assets && yarn && cd ..
  - chromium-browser --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - mix test --max-cases 1
  - cd assets && yarn run deploy
